# db/seeds/location.rb

Location.delete_all

Location.create!(name: 'Trolley 1', location_type: 'trolley', sort_order: 1, active: true)
Location.create!(name: 'Trolley 2', location_type: 'trolley', sort_order: 2, active: true)
Location.create!(name: 'Trolley 3', location_type: 'trolley', sort_order: 3, active: true)
Location.create!(name: 'Trolley 4', location_type: 'trolley', sort_order: 4, active: true)
Location.create!(name: 'Trolley 5', location_type: 'trolley', sort_order: 5, active: true)
Location.create!(name: 'Trolley 6', location_type: 'trolley', sort_order: 6, active: true)
Location.create!(name: 'Trolley 7', location_type: 'trolley', sort_order: 7, active: true)
Location.create!(name: 'Trolley 8', location_type: 'trolley', sort_order: 8, active: true)
Location.create!(name: 'Trolley 9', location_type: 'trolley', sort_order: 9, active: true)
Location.create!(name: 'Trolley 10', location_type: 'trolley', sort_order: 10, active: true)
Location.create!(name: 'Trolley 11', location_type: 'trolley', sort_order: 11, active: true)
Location.create!(name: 'Trolley 12', location_type: 'trolley', sort_order: 12, active: true)
Location.create!(name: 'Trolley 13', location_type: 'trolley', sort_order: 13, active: true)
Location.create!(name: 'Trolley 14', location_type: 'trolley', sort_order: 14, active: true)
Location.create!(name: 'Trolley 15', location_type: 'trolley', sort_order: 15, active: true)
Location.create!(name: 'Trolley 16', location_type: 'trolley', sort_order: 16, active: true)
Location.create!(name: 'Trolley 17', location_type: 'trolley', sort_order: 17, active: true)
Location.create!(name: 'Trolley 18', location_type: 'trolley', sort_order: 18, active: true)
Location.create!(name: 'Trolley 19', location_type: 'trolley', sort_order: 19, active: true)
Location.create!(name: 'Trolley 20', location_type: 'trolley', sort_order: 20, active: true)
Location.create!(name: 'Trolley 21', location_type: 'trolley', sort_order: 21, active: true)
Location.create!(name: 'Trolley 22', location_type: 'trolley', sort_order: 22, active: true)
Location.create!(name: 'Trolley 23', location_type: 'trolley', sort_order: 23, active: true)
Location.create!(name: 'Trolley 24', location_type: 'trolley', sort_order: 24, active: true)
Location.create!(name: 'Trolley 25', location_type: 'trolley', sort_order: 25, active: true)
Location.create!(name: 'Trolley 26', location_type: 'trolley', sort_order: 26, active: true)
Location.create!(name: 'Trolley 27', location_type: 'trolley', sort_order: 27, active: true)
Location.create!(name: 'Trolley 28', location_type: 'trolley', sort_order: 28, active: true)
Location.create!(name: 'Trolley 29', location_type: 'trolley', sort_order: 29, active: true)
Location.create!(name: 'Trolley 30', location_type: 'trolley', sort_order: 30, active: true)
Location.create!(name: 'Trolley 31', location_type: 'trolley', sort_order: 31, active: true)
Location.create!(name: 'Trolley 32', location_type: 'trolley', sort_order: 32, active: true)
Location.create!(name: 'Trolley 33', location_type: 'trolley', sort_order: 33, active: true)
Location.create!(name: 'Trolley 34', location_type: 'trolley', sort_order: 34, active: true)
Location.create!(name: 'Trolley 35', location_type: 'trolley', sort_order: 35, active: true)
Location.create!(name: 'Trolley 36', location_type: 'trolley', sort_order: 36, active: true)
Location.create!(name: 'Trolley 37', location_type: 'trolley', sort_order: 37, active: true)
Location.create!(name: 'Trolley 38', location_type: 'trolley', sort_order: 38, active: true)
Location.create!(name: 'Trolley 39', location_type: 'trolley', sort_order: 39, active: true)
Location.create!(name: 'Trolley 40', location_type: 'trolley', sort_order: 40, active: true)
Location.create!(name: 'Trolley 41', location_type: 'trolley', sort_order: 41, active: true)
Location.create!(name: 'Trolley 42', location_type: 'trolley', sort_order: 42, active: true)
Location.create!(name: 'Trolley 43', location_type: 'trolley', sort_order: 43, active: true)
Location.create!(name: 'Trolley 44', location_type: 'trolley', sort_order: 44, active: true)
Location.create!(name: 'Trolley 45', location_type: 'trolley', sort_order: 45, active: true)
Location.create!(name: 'Trolley 46', location_type: 'trolley', sort_order: 46, active: true)
Location.create!(name: 'Trolley 47', location_type: 'trolley', sort_order: 47, active: true)
Location.create!(name: 'Trolley 48', location_type: 'trolley', sort_order: 48, active: true)
Location.create!(name: 'Trolley 49', location_type: 'trolley', sort_order: 49, active: true)
Location.create!(name: 'Trolley 50', location_type: 'trolley', sort_order: 50, active: true)
Location.create!(name: 'Trolley 51', location_type: 'trolley', sort_order: 51, active: true)
Location.create!(name: 'Trolley 52', location_type: 'trolley', sort_order: 52, active: true)
Location.create!(name: 'Trolley 53', location_type: 'trolley', sort_order: 53, active: true)
Location.create!(name: 'Trolley 54', location_type: 'trolley', sort_order: 54, active: true)
Location.create!(name: 'Trolley 55', location_type: 'trolley', sort_order: 55, active: true)
Location.create!(name: 'Trolley 56', location_type: 'trolley', sort_order: 56, active: true)
Location.create!(name: 'Trolley 57', location_type: 'trolley', sort_order: 57, active: true)
Location.create!(name: 'Trolley 58', location_type: 'trolley', sort_order: 58, active: true)
Location.create!(name: 'Trolley 59', location_type: 'trolley', sort_order: 59, active: true)
Location.create!(name: 'Trolley 60', location_type: 'trolley', sort_order: 60, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 1', location_type: 'alley', sort_order: 61, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 2', location_type: 'alley', sort_order: 62, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 3', location_type: 'alley', sort_order: 63, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 4', location_type: 'alley', sort_order: 64, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 5', location_type: 'alley', sort_order: 65, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 6', location_type: 'alley', sort_order: 66, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 7', location_type: 'alley', sort_order: 67, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 8', location_type: 'alley', sort_order: 68, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 9', location_type: 'alley', sort_order: 69, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 10', location_type: 'alley', sort_order: 70, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 11', location_type: 'alley', sort_order: 71, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 12', location_type: 'alley', sort_order: 72, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 13', location_type: 'alley', sort_order: 73, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 14', location_type: 'alley', sort_order: 74, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 15', location_type: 'alley', sort_order: 75, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 16', location_type: 'alley', sort_order: 76, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 17', location_type: 'alley', sort_order: 77, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 18', location_type: 'alley', sort_order: 78, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 19', location_type: 'alley', sort_order: 79, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 20', location_type: 'alley', sort_order: 80, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 21', location_type: 'alley', sort_order: 81, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 22', location_type: 'alley', sort_order: 82, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 23', location_type: 'alley', sort_order: 83, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 24', location_type: 'alley', sort_order: 84, active: true)
Location.create!(name: 'Shed 4 : Alley 1 : Column 25', location_type: 'alley', sort_order: 85, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 1', location_type: 'alley', sort_order: 86, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 2', location_type: 'alley', sort_order: 87, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 3', location_type: 'alley', sort_order: 88, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 4', location_type: 'alley', sort_order: 89, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 5', location_type: 'alley', sort_order: 90, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 6', location_type: 'alley', sort_order: 91, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 7', location_type: 'alley', sort_order: 92, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 8', location_type: 'alley', sort_order: 93, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 9', location_type: 'alley', sort_order: 94, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 10', location_type: 'alley', sort_order: 95, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 11', location_type: 'alley', sort_order: 96, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 12', location_type: 'alley', sort_order: 97, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 13', location_type: 'alley', sort_order: 98, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 14', location_type: 'alley', sort_order: 99, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 15', location_type: 'alley', sort_order: 100, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 16', location_type: 'alley', sort_order: 101, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 17', location_type: 'alley', sort_order: 102, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 18', location_type: 'alley', sort_order: 103, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 19', location_type: 'alley', sort_order: 104, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 20', location_type: 'alley', sort_order: 105, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 21', location_type: 'alley', sort_order: 106, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 22', location_type: 'alley', sort_order: 107, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 23', location_type: 'alley', sort_order: 108, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 24', location_type: 'alley', sort_order: 109, active: true)
Location.create!(name: 'Shed 4 : Alley 2 : Column 25', location_type: 'alley', sort_order: 110, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 1', location_type: 'alley', sort_order: 111, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 2', location_type: 'alley', sort_order: 112, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 3', location_type: 'alley', sort_order: 113, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 4', location_type: 'alley', sort_order: 114, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 5', location_type: 'alley', sort_order: 115, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 6', location_type: 'alley', sort_order: 116, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 7', location_type: 'alley', sort_order: 117, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 8', location_type: 'alley', sort_order: 118, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 9', location_type: 'alley', sort_order: 119, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 10', location_type: 'alley', sort_order: 120, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 11', location_type: 'alley', sort_order: 121, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 12', location_type: 'alley', sort_order: 122, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 13', location_type: 'alley', sort_order: 123, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 14', location_type: 'alley', sort_order: 124, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 15', location_type: 'alley', sort_order: 125, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 16', location_type: 'alley', sort_order: 126, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 17', location_type: 'alley', sort_order: 127, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 18', location_type: 'alley', sort_order: 128, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 19', location_type: 'alley', sort_order: 129, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 20', location_type: 'alley', sort_order: 130, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 21', location_type: 'alley', sort_order: 131, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 22', location_type: 'alley', sort_order: 132, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 23', location_type: 'alley', sort_order: 133, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 24', location_type: 'alley', sort_order: 134, active: true)
Location.create!(name: 'Shed 4 : Alley 3 : Column 25', location_type: 'alley', sort_order: 135, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 1', location_type: 'alley', sort_order: 136, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 2', location_type: 'alley', sort_order: 137, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 3', location_type: 'alley', sort_order: 138, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 4', location_type: 'alley', sort_order: 139, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 5', location_type: 'alley', sort_order: 140, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 6', location_type: 'alley', sort_order: 141, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 7', location_type: 'alley', sort_order: 142, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 8', location_type: 'alley', sort_order: 143, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 9', location_type: 'alley', sort_order: 144, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 10', location_type: 'alley', sort_order: 145, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 11', location_type: 'alley', sort_order: 146, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 12', location_type: 'alley', sort_order: 147, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 13', location_type: 'alley', sort_order: 148, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 14', location_type: 'alley', sort_order: 149, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 15', location_type: 'alley', sort_order: 150, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 16', location_type: 'alley', sort_order: 151, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 17', location_type: 'alley', sort_order: 152, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 18', location_type: 'alley', sort_order: 153, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 19', location_type: 'alley', sort_order: 154, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 20', location_type: 'alley', sort_order: 155, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 21', location_type: 'alley', sort_order: 156, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 22', location_type: 'alley', sort_order: 157, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 23', location_type: 'alley', sort_order: 158, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 24', location_type: 'alley', sort_order: 159, active: true)
Location.create!(name: 'Shed 4 : Alley 4 : Column 25', location_type: 'alley', sort_order: 160, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 1', location_type: 'alley', sort_order: 161, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 2', location_type: 'alley', sort_order: 162, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 3', location_type: 'alley', sort_order: 163, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 4', location_type: 'alley', sort_order: 164, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 5', location_type: 'alley', sort_order: 165, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 6', location_type: 'alley', sort_order: 166, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 7', location_type: 'alley', sort_order: 167, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 8', location_type: 'alley', sort_order: 168, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 9', location_type: 'alley', sort_order: 169, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 10', location_type: 'alley', sort_order: 170, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 11', location_type: 'alley', sort_order: 171, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 12', location_type: 'alley', sort_order: 172, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 13', location_type: 'alley', sort_order: 173, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 14', location_type: 'alley', sort_order: 174, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 15', location_type: 'alley', sort_order: 175, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 16', location_type: 'alley', sort_order: 176, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 17', location_type: 'alley', sort_order: 177, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 18', location_type: 'alley', sort_order: 178, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 19', location_type: 'alley', sort_order: 179, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 20', location_type: 'alley', sort_order: 180, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 21', location_type: 'alley', sort_order: 181, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 22', location_type: 'alley', sort_order: 182, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 23', location_type: 'alley', sort_order: 183, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 24', location_type: 'alley', sort_order: 184, active: true)
Location.create!(name: 'Shed 4 : Alley 5 : Column 25', location_type: 'alley', sort_order: 185, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 1', location_type: 'alley', sort_order: 186, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 2', location_type: 'alley', sort_order: 187, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 3', location_type: 'alley', sort_order: 188, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 4', location_type: 'alley', sort_order: 189, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 5', location_type: 'alley', sort_order: 190, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 6', location_type: 'alley', sort_order: 191, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 7', location_type: 'alley', sort_order: 192, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 8', location_type: 'alley', sort_order: 193, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 9', location_type: 'alley', sort_order: 194, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 10', location_type: 'alley', sort_order: 195, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 11', location_type: 'alley', sort_order: 196, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 12', location_type: 'alley', sort_order: 197, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 13', location_type: 'alley', sort_order: 198, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 14', location_type: 'alley', sort_order: 199, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 15', location_type: 'alley', sort_order: 200, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 16', location_type: 'alley', sort_order: 201, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 17', location_type: 'alley', sort_order: 202, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 18', location_type: 'alley', sort_order: 203, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 19', location_type: 'alley', sort_order: 204, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 20', location_type: 'alley', sort_order: 205, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 21', location_type: 'alley', sort_order: 206, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 22', location_type: 'alley', sort_order: 207, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 23', location_type: 'alley', sort_order: 208, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 24', location_type: 'alley', sort_order: 209, active: true)
Location.create!(name: 'Shed 4 : Alley 6 : Column 25', location_type: 'alley', sort_order: 210, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 1', location_type: 'alley', sort_order: 211, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 2', location_type: 'alley', sort_order: 212, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 3', location_type: 'alley', sort_order: 213, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 4', location_type: 'alley', sort_order: 214, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 5', location_type: 'alley', sort_order: 215, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 6', location_type: 'alley', sort_order: 216, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 7', location_type: 'alley', sort_order: 217, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 8', location_type: 'alley', sort_order: 218, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 9', location_type: 'alley', sort_order: 219, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 10', location_type: 'alley', sort_order: 220, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 11', location_type: 'alley', sort_order: 221, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 12', location_type: 'alley', sort_order: 222, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 13', location_type: 'alley', sort_order: 223, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 14', location_type: 'alley', sort_order: 224, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 15', location_type: 'alley', sort_order: 225, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 16', location_type: 'alley', sort_order: 226, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 17', location_type: 'alley', sort_order: 227, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 18', location_type: 'alley', sort_order: 228, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 19', location_type: 'alley', sort_order: 229, active: true)
Location.create!(name: 'Shed 5 : Alley 1 : Column 20', location_type: 'alley', sort_order: 230, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 1', location_type: 'alley', sort_order: 231, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 2', location_type: 'alley', sort_order: 232, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 3', location_type: 'alley', sort_order: 233, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 4', location_type: 'alley', sort_order: 234, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 5', location_type: 'alley', sort_order: 235, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 6', location_type: 'alley', sort_order: 236, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 7', location_type: 'alley', sort_order: 237, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 8', location_type: 'alley', sort_order: 238, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 9', location_type: 'alley', sort_order: 239, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 10', location_type: 'alley', sort_order: 240, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 11', location_type: 'alley', sort_order: 241, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 12', location_type: 'alley', sort_order: 242, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 13', location_type: 'alley', sort_order: 243, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 14', location_type: 'alley', sort_order: 244, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 15', location_type: 'alley', sort_order: 245, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 16', location_type: 'alley', sort_order: 246, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 17', location_type: 'alley', sort_order: 247, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 18', location_type: 'alley', sort_order: 248, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 19', location_type: 'alley', sort_order: 249, active: true)
Location.create!(name: 'Shed 5 : Alley 2 : Column 20', location_type: 'alley', sort_order: 250, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 1', location_type: 'alley', sort_order: 251, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 2', location_type: 'alley', sort_order: 252, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 3', location_type: 'alley', sort_order: 253, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 4', location_type: 'alley', sort_order: 254, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 5', location_type: 'alley', sort_order: 255, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 6', location_type: 'alley', sort_order: 256, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 7', location_type: 'alley', sort_order: 257, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 8', location_type: 'alley', sort_order: 258, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 9', location_type: 'alley', sort_order: 259, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 10', location_type: 'alley', sort_order: 260, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 11', location_type: 'alley', sort_order: 261, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 12', location_type: 'alley', sort_order: 262, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 13', location_type: 'alley', sort_order: 263, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 14', location_type: 'alley', sort_order: 264, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 15', location_type: 'alley', sort_order: 265, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 16', location_type: 'alley', sort_order: 266, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 17', location_type: 'alley', sort_order: 267, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 18', location_type: 'alley', sort_order: 268, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 19', location_type: 'alley', sort_order: 269, active: true)
Location.create!(name: 'Shed 5 : Alley 3 : Column 20', location_type: 'alley', sort_order: 270, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 1', location_type: 'alley', sort_order: 271, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 2', location_type: 'alley', sort_order: 272, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 3', location_type: 'alley', sort_order: 273, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 4', location_type: 'alley', sort_order: 274, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 5', location_type: 'alley', sort_order: 275, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 6', location_type: 'alley', sort_order: 276, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 7', location_type: 'alley', sort_order: 277, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 8', location_type: 'alley', sort_order: 278, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 9', location_type: 'alley', sort_order: 279, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 10', location_type: 'alley', sort_order: 280, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 11', location_type: 'alley', sort_order: 281, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 12', location_type: 'alley', sort_order: 282, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 13', location_type: 'alley', sort_order: 283, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 14', location_type: 'alley', sort_order: 284, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 15', location_type: 'alley', sort_order: 285, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 16', location_type: 'alley', sort_order: 286, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 17', location_type: 'alley', sort_order: 287, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 18', location_type: 'alley', sort_order: 288, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 19', location_type: 'alley', sort_order: 289, active: true)
Location.create!(name: 'Shed 5 : Alley 4 : Column 20', location_type: 'alley', sort_order: 290, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 1', location_type: 'alley', sort_order: 291, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 2', location_type: 'alley', sort_order: 292, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 3', location_type: 'alley', sort_order: 293, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 4', location_type: 'alley', sort_order: 294, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 5', location_type: 'alley', sort_order: 295, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 6', location_type: 'alley', sort_order: 296, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 7', location_type: 'alley', sort_order: 297, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 8', location_type: 'alley', sort_order: 298, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 9', location_type: 'alley', sort_order: 299, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 10', location_type: 'alley', sort_order: 300, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 11', location_type: 'alley', sort_order: 301, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 12', location_type: 'alley', sort_order: 302, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 13', location_type: 'alley', sort_order: 303, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 14', location_type: 'alley', sort_order: 304, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 15', location_type: 'alley', sort_order: 305, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 16', location_type: 'alley', sort_order: 306, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 17', location_type: 'alley', sort_order: 307, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 18', location_type: 'alley', sort_order: 308, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 19', location_type: 'alley', sort_order: 309, active: true)
Location.create!(name: 'Shed 5 : Alley 5 : Column 20', location_type: 'alley', sort_order: 310, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 1', location_type: 'alley', sort_order: 311, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 2', location_type: 'alley', sort_order: 312, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 3', location_type: 'alley', sort_order: 313, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 4', location_type: 'alley', sort_order: 314, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 5', location_type: 'alley', sort_order: 315, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 6', location_type: 'alley', sort_order: 316, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 7', location_type: 'alley', sort_order: 317, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 8', location_type: 'alley', sort_order: 318, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 9', location_type: 'alley', sort_order: 319, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 10', location_type: 'alley', sort_order: 320, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 11', location_type: 'alley', sort_order: 321, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 12', location_type: 'alley', sort_order: 322, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 13', location_type: 'alley', sort_order: 323, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 14', location_type: 'alley', sort_order: 324, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 15', location_type: 'alley', sort_order: 325, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 16', location_type: 'alley', sort_order: 326, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 17', location_type: 'alley', sort_order: 327, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 18', location_type: 'alley', sort_order: 328, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 19', location_type: 'alley', sort_order: 329, active: true)
Location.create!(name: 'Shed 5 : Alley 6 : Column 20', location_type: 'alley', sort_order: 330, active: true)