name: RSpec

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: poacher_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      # Point Rails at the CI Postgres service and your test DB name:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/poacher_test
      # Optional: title assertions off by default in CI (flip to "true" if you like)
      ASSERT_TITLES: "false"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version # Uses the version from your repo
          bundler-cache: true # Caches gems between runs

      # If you have JS tooling (esbuild/vite/webpack), uncomment:
      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: yarn install --frozen-lockfile

      - name: Prepare database
        run: |
          bin/rails db:prepare

      # 🚦 Fast gate: run your smoke spec first
      - name: Run smoke spec
        run: |
          bundle exec rspec spec/features/page_smoke_primary_navigation_spec.rb --format progress

      # 🧪 Then run everything else
      - name: Run full test suite
        run: |
          bundle exec rspec --format progress

      # 📊 Save SimpleCov HTML (if you use it)
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
