require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/delivery_inspections", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DeliveryInspection. As you add validations to DeliveryInspection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeliveryInspection.create! valid_attributes
      get delivery_inspections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      delivery_inspection = DeliveryInspection.create! valid_attributes
      get delivery_inspection_url(delivery_inspection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_delivery_inspection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      delivery_inspection = DeliveryInspection.create! valid_attributes
      get edit_delivery_inspection_url(delivery_inspection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeliveryInspection" do
        expect {
          post delivery_inspections_url, params: { delivery_inspection: valid_attributes }
        }.to change(DeliveryInspection, :count).by(1)
      end

      it "redirects to the created delivery_inspection" do
        post delivery_inspections_url, params: { delivery_inspection: valid_attributes }
        expect(response).to redirect_to(delivery_inspection_url(DeliveryInspection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeliveryInspection" do
        expect {
          post delivery_inspections_url, params: { delivery_inspection: invalid_attributes }
        }.to change(DeliveryInspection, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post delivery_inspections_url, params: { delivery_inspection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested delivery_inspection" do
        delivery_inspection = DeliveryInspection.create! valid_attributes
        patch delivery_inspection_url(delivery_inspection), params: { delivery_inspection: new_attributes }
        delivery_inspection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the delivery_inspection" do
        delivery_inspection = DeliveryInspection.create! valid_attributes
        patch delivery_inspection_url(delivery_inspection), params: { delivery_inspection: new_attributes }
        delivery_inspection.reload
        expect(response).to redirect_to(delivery_inspection_url(delivery_inspection))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        delivery_inspection = DeliveryInspection.create! valid_attributes
        patch delivery_inspection_url(delivery_inspection), params: { delivery_inspection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested delivery_inspection" do
      delivery_inspection = DeliveryInspection.create! valid_attributes
      expect {
        delete delivery_inspection_url(delivery_inspection)
      }.to change(DeliveryInspection, :count).by(-1)
    end

    it "redirects to the delivery_inspections list" do
      delivery_inspection = DeliveryInspection.create! valid_attributes
      delete delivery_inspection_url(delivery_inspection)
      expect(response).to redirect_to(delivery_inspections_url)
    end
  end
end
