require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/validation_ranges", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ValidationRange. As you add validations to ValidationRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ValidationRange.create! valid_attributes
      get validation_ranges_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      validation_range = ValidationRange.create! valid_attributes
      get validation_range_url(validation_range)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_validation_range_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      validation_range = ValidationRange.create! valid_attributes
      get edit_validation_range_url(validation_range)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ValidationRange" do
        expect {
          post validation_ranges_url, params: { validation_range: valid_attributes }
        }.to change(ValidationRange, :count).by(1)
      end

      it "redirects to the created validation_range" do
        post validation_ranges_url, params: { validation_range: valid_attributes }
        expect(response).to redirect_to(validation_range_url(ValidationRange.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ValidationRange" do
        expect {
          post validation_ranges_url, params: { validation_range: invalid_attributes }
        }.to change(ValidationRange, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post validation_ranges_url, params: { validation_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested validation_range" do
        validation_range = ValidationRange.create! valid_attributes
        patch validation_range_url(validation_range), params: { validation_range: new_attributes }
        validation_range.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the validation_range" do
        validation_range = ValidationRange.create! valid_attributes
        patch validation_range_url(validation_range), params: { validation_range: new_attributes }
        validation_range.reload
        expect(response).to redirect_to(validation_range_url(validation_range))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        validation_range = ValidationRange.create! valid_attributes
        patch validation_range_url(validation_range), params: { validation_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested validation_range" do
      validation_range = ValidationRange.create! valid_attributes
      expect {
        delete validation_range_url(validation_range)
      }.to change(ValidationRange, :count).by(-1)
    end

    it "redirects to the validation_ranges list" do
      validation_range = ValidationRange.create! valid_attributes
      delete validation_range_url(validation_range)
      expect(response).to redirect_to(validation_ranges_url)
    end
  end
end
