json.extract! grading_note,
              :id,
              :makesheet_id,
              :date,
              :appearance,
              :bore,
              :texture,
              :taste,
              :score,
              :head_taster_id,
              :taster_1_name,
              :taster_2_name,
              :created_at,
              :updated_at
