# .github/workflows/smoke.yml
name: Smoke Test

on:
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: poacher_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/poacher_test
      ASSERT_TITLES: "false"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # If you use cssbundling/esbuild/vite/webpack, include Node:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # If you have a package.json (cssbundling etc.), install deps:
      - name: Install JS deps
        if: hashFiles('package.json') != ''
        run: |
          if [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; \
          elif [ -f package-lock.json ]; then npm ci; \
          else npm i; fi

      - name: Precompile assets
        run: |
          bin/rails assets:precompile

      - name: Prepare database
        run: |
          bin/rails db:prepare

      - name: Run smoke spec
        run: |
          bundle exec rspec spec/features/page_smoke_primary_navigation_spec.rb --format progress
